### ISSUE TITLE
Accessibility ??

### ISSUE THREAD

**Issue by cloudsolace** [luncheon/flex-splitter-directive#10]
Is it possible to add keyboard support?

**Comment by luncheon** [comment]
It would be better to support keyboard. I'll try to implement it. Thanks.

**Comment by luncheon** [comment]
v0.4.0 with keyboard support is released.
- To handle cursor keys, add `tabindex="1"` to the `separator`:  
  ```html
  <div role="separator" tabindex="1"></div>
  ```
- To specify the amount of movement by cursor keys, set `keyboard-movement:n` to the `data-flex-splitter-horizontal` or `data-flex-splitter-vertical` attribute of the splitter container:  
  ```html
  <div data-flex-splitter-horizontal="keyboard-movement:10">
  ```
