### ISSUE TITLE
Drag events needed for better control 

### ISSUE THREAD

**Issue by cloudsolace** [luncheon/flex-splitter-directive#11]
onDrag | Function |   | Callback on drag.
onDragStart | Function |   | Callback on drag start.
onDragEnd | Function |   | Callback on drag end.

**Comment by luncheon** [comment]
Use `addEventListener("pointerdown", callback)` etc. as usual.
I think it is not necessary for this library to provide these event APIs.

**Comment by cloudsolace** [comment]
Perfect thanks for providing insights how this can be achieved.
