### ISSUE TITLE
Programmatically control sizes 

### ISSUE THREAD

**Issue by cloudsolace** [luncheon/flex-splitter-directive#12]
setSizes([id, id1, id2]) --- > sets panel size
getSizes() ---> gets the current sizes of the panel
setMinSize(id, width)  ---> set min size of a panel
getMinSize(id) ---> get min size of a panel
collapse(id) ---> collapse panel based on index or id
expand(id) ---> expand panel based on index or id

**Comment by luncheon** [comment]
All of these can be done by calling the standard DOM API.

- setSizes: ``element.style.width = `${n}px` ``
- getSizes: `element.offsetWidth`
- setMinSize: ``element.style.minWidth = `${n}px` ``
- getMinSize: `parseInt(getComputedStyle(element).minWidth, 10)`
- collapse: `element.style.width = "0"`
- expand: `element.style.width = "20vw"`

This package is intended to be a very small library that can be used without scripting.
Currently, I do not plan to provide these APIs. Sorry.

**Comment by cloudsolace** [comment]
Perfect thanks for providing insights how this can be achieved.
